spring:
  application:
    name: test-hello-reqlimit
  redis:
    host: 0.0.0.0
    port: 16379
    password: Aa12345!
  cloud:
    gateway:
      routes:
        - id: path_test
          predicates:
            - Path=/gateway/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                denyEmptyKey: false
                emptyKeyStatus: SERVICE_UNAVAILABLE
                keyResolver: '#{@rateLimterKeyResolver}'
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
            - StripPrefix=1
          uri: http://www.baidu.com

server:
  port: 8080

