spring:
  application:
    name: test-hello-reqlimit
  redis:
    host: 0.0.0.0
    port: 16379
    password: Aa12345!
  cloud:
    gateway:
      routes:
        - id: multiple_test
          predicates:
            - Path=/gateway/multiple/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                denyEmptyKey: false
                emptyKeyStatus: SERVICE_UNAVAILABLE
                keyResolver: '#{@multipleRateLimterKeyResolver}'
                rateLimiter: '#{@multipleRateLimter}'
                redis-rate-limiter.replenishRate: 10 # 每秒补充10个
                redis-rate-limiter.burstCapacity: 20 # 突发20个
            - StripPrefix=1
          uri: http://www.baidu.com
server:
  port: 8080

