spring:
  application:
    name: test-hello-gateway
  cloud:
    gateway:
      routes:
        - id: path_test
          predicates:
            - Path=/gateway_path_test/**
            - name: ReadBody
              args:
                inClass: "#{T(String)}"
                predicate: "#{@requestBodyCachePredicate}"
          filters:
            - StripPrefix=1
            - name: ModifyPostParams
          uri: http://0.0.0.0:8080
          # eg. http://0.0.0.0:8000/gateway_path_test/yong-test-hello/hello-api/hello --> http://0.0.0.0:8080/yong-test-hello/hello-api/hello
          # eg. http://0.0.0.0:8000/gateway_path_test/yong-test-hello/hello-api/sayhello/yong --> http://0.0.0.0:8080/yong-test-hello/hello-api/sayhello/yong

server:
  port: 8000