mybatis:
  mapper-locations: classpath:mapper/**/*xml
spring:
  datasource:
    name: fuck-test
    url: jdbc:postgresql://0.0.0.0:5432/postgres
    username: yuyong
    password: 123456
    driver-class-name: org.postgresql.Driver
server:
  port: 8000