server:
  port: 8000

spring:
  datasource:
    name: fuck-test
    url: jdbc:mysql://localhost:3306/yong?serverTimezone=UTC
    username: yong
    password: Yong!9911214
    driver-class-name: 'com.mysql.cj.jdbc.Driver'